%MATLAB Code from Sensor Array Analyzer App

%Generated by MATLAB 9.5 and Phased Array System Toolbox 4.0

%Generated on 12-Feb-2019 16:42:52

% Create an arbitrary geometry array
h = phased.ConformalArray();
h.ElementPosition = [0 0 0 0;0 0.0428571428571429 0 ...
    0;0.0428571428571429 0 0 0];
h.ElementNormal = [0 10 0 0;0 20 0 20];
%Calculate Taper
wind = ones(1,4);
h.Taper = wind;
%Create Isotropic Antenna Element
el = phased.IsotropicAntennaElement;
h.Element = el;
%Assign steering angles, frequencies and propagation speed
SA = [20;20];
%Assign number of phase shift quantization bits
PSB = 0;
F = 3500000000;
PS = 300000000;
%Create figure, panel, and axes
fig = figure;
panel = uipanel('Parent',fig);
hAxes = axes('Parent',panel,'Color','none');
%Calculate Steering Weights
w = zeros(getNumElements(h), length(F));
SV = phased.SteeringVector('SensorArray',h, 'PropagationSpeed', PS);
%Find the weights
for idx = 1:length(F)
    w(:, idx) = step(SV, F(idx), SA(:, idx))
end
%Plot 3d graph
fmt = 'polar';
pattern(h, F(1), 'PropagationSpeed', PS, 'Type','directivity', ...
    'CoordinateSystem', fmt,'weights', w(:,1));
%Adjust the view angles
view(hAxes,[-17.6895594040642 -17.3419664502217]);
title = get(hAxes, 'title');
title_str = get(title, 'String');
%Modify the title
[Fval, ~, Fletter] = engunits(3500000000);
steeringString = 'steered at 30 Az, 20 El';
title_str = [title_str sprintf('\n') num2str(Fval) ' ' Fletter 'Hz ' ...
    steeringString];
set(title, 'String', title_str);
